![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)
# $$🌈\textbf{ TODOs for LAB1 - 2 Python Basic  } 🌙$$
## **<font color = "red">These are the same TODOs </font>as in the Corresponding LAB**
## ✍ **Complete all questions in each of the $\color{green}{\textbf{TODOs}}$ from the LAB.**
### **1.** Click ▶ to view the problem detail
### **2.** Refer to the code you learned from Lessons with Code and LABs.
### **3.** Always use **`f-string`** to print out the results for each problem.
### **4.** Plots should include a title and labels for the x and y axes.
#### $\color{magenta}{\textbf{ NOTE: }}$ It is strongly recommended that you need to understand the relevant concepts and learn the necessary statistical programming for computation with Python taught in the video lessons or labs and have completed the worksheets for the lessons and Lab before attempting the TODOs.

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)
### **Numbers in Python**

###**$\color{green}{\textbf{TO DO 1:}}$ Practice Representations of Numbers in Python**

1. Create four Code cells and enter
* a positive decimal,
* negative integer,
* a fraction, and
* number in the magnitude of $10^{4}$, respectly

2. Verify that the output is the same as the number you typed into the Code cell after you run the cells.

In [1]:
# TO DO 1.1.1
answer = 1.6
print(f"TO DO 1.1.1: {answer}")

TO DO 1.1: 1.6


In [2]:
# TO DO 1.1.2
answer = -6
print(f"TO DO 1.1.2: {answer}")

TO DO 1.1.2: -6


In [4]:
# TO DO 1.1.3
answer = 1/5
print(f"TO DO 1.1.3: {answer}")

TO DO 1.1.3: 0.2


In [12]:
# TO DO 1.1.4
answer = 10.56e3
print(f"TO DO 1.1.4: {answer}")

TO DO 1.1.4: 10560.0


###**$\color{green}{\textbf{TO DO 2:}}$**
Create a Code cell and type some numbers that are greated than 1000 with comma(s) as placement. In a markdown cell to document what you observe in the outcome

In [18]:
100,150,234

(100, 150, 234)

When I enter the number with commas `100,150,234` (one hundred million, one hundred and fifty thousand, two hundred and thirty four), Python interprets the commas as if I want to create a tuple (even though it is not enclosed in parentheses), which is why the output looks like `(100, 150, 234)`. We can verify that this is a tuple by running the following
```python
answer = 100,150,234
assert type(answer) == tuple
```

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)
## **Arithematic Operations of Numbers:**


<details>
  <summary><b>Basic Arithmetic Operations</b> </summary>

|Symbol|Basic Arithmitic|Python function|
|:--:|:--:|:--:|
|$+$|  Addtion||
|$-$|  Subtraction||
|$*$| Multiplication||
|/| Floating-point division||
|//| Ineger division||
|%| Modulus (reminder in division||
|**| exponentiation|math.exp()|
|** (1/2)|Square root|math.sqrt()

</details>

<details>
  <summary><b>Python arithmetic oeprator precedence</b></summary>

|Operators|Precedence|
|:--:|:--:|
|**|(Highest precedence)|
|*, /, //, %||
|$+,-$|(Lowest precedence)|

</details>


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)
### **$\color{green}{\textbf{TO DO 3:}}$**  Write code for a subtraction of one negtive number and a number with negative exponent

In [20]:
# TO DO 3.1
answer = 3 - (-5)
print(f"TO DO 3.1: {answer}")

TO DO 3.1: 8


In [22]:
# TO DO 3.2
answer = 3**(-2)
print(f"TO DO 3.2: {answer}")

TO DO 3.2: 0.1111111111111111


---

### **$\color{green}{\textbf{TO DO 4:}}$**  write code to evaluate the expression $ \frac{2.3+3.5+8.1+(-0.5)}{\sqrt{23}}$.  Verify that the output is $2.794093148364802$

In [24]:
from math import sqrt

answer = (2.3 + 3.5 + 8.1 + (-0.5))/sqrt(23)
print(f"TO DO 4: {answer}")

TO DO 4: 2.794093148364802


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)
# **Conditionals**
  We make decisions based on the conditions at that moement throughout a day.  For example, It is noon time, if I am free, I will have lunch.  I will have lunch if I don't have time.  The social distancing is still reenforced,so I take classes online.  You are hungery, so eat something. Many of these conditionls have the if-then or if-then-else structures.  Python have conditional statements to handle this.      We have learned variable containers and boolean operators.  In this section, we will we will combine them to create conditionals so that we can make choices.  But we have not use both of them in the same line of code.


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)
## **If Statement**

 <code> if some_condition_thats_True_or_False:<br></code>
           $\hspace{10mm}$action                 </code>

The condition - the part after the if and before the semicolon must be a boolean expressions or combined boolean expressions, that is, a $\color{blue}{\text{True}}$ or $\color{blue}{\text{False}}$ statement.  Python also use "$\color{blue}{1}$" for True and "$\color{blue}{0}$" for False.

###🧚 **$\color{orange}{\textbf{Tip:}}$ Must have indentation for all Python code for actions in each if-statement. (usually four white spaces)**

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)
## **Else**
Else provides conditions for more than one choices
```
  Else provides conditions for more than one choices.
   if its_hot_outside:
     ware_a_T_Shirt
  else:
    ware_a_Sweather
  ```

### 🔖 **$\color{green}{\textbf{ TO DO 5:}}$** Modify the code below so that it prints "Bye!".

In [25]:
if 3 < 1:
    print("Hi!")
else:           # this line is ignored  if the condition is True
    print("Bye!")  # this line is ignored  if the condition is True

Bye!
